config/routes.rb
Rails.application.routes.draw do
  #resources :orders
  #get 'orders/index'
  #get 'order/show'
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'

  root 'store#index', as: 'store_index'
  resources :line_items
  #resources :carts
  get 'cart', to: 'carts#index'
  post 'carts', to: 'carts#create', as: 'cart_checkout'

  get 'line_items/index'
  get 'line_items/show'
  get 'line_items/new'
  get 'line_items/create'
  post 'line_items/destroy', to: 'line_items#destroy', as: 'delete_line_item'
  get 'store/index', as: 'store_index_path'

  #resources :line_items, except: :edit
  #resources :line_items, only: :edit
  resources :users
  resources :foods
  resources :categories

  get '/login', to: 'sessions#login', as: 'login'
  post 'login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :orders, only: [:index, :show, :edit, :update] do
    member do
      get :cancel
      get :paid
      get :completed
    end
    collection do
      get :cancel_all
    end
  end
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :calculate_subtotal_order
  layout :get_layout
  before_action :current_order

  def get_layout
    Current.user.is_admin ? 'admin' : 'application'
  end

  # GET /orders or /orders.json
  def index
    user = User.find_by_id(Current.user.id)

    if Current.user.is_admin
      @orders = Order.all
    else
      @orders = Order.where(user_id: user.id)
    end

    @pagy, @records = pagy(@orders, items: 5)
  end

  # GET /orders/1 or /orders/1.json
  def show
    session[:order_id] = params[:id]
    current_order
    calculate_subtotal_order
    @line_items = LineItem.where(order_id: Current.order_selected.id)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # GET /orders/1/cancel
  def cancel
    order = Order.find(params[:id])
    order.status = "cancelled"
    order.save

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was updated status." }
    end
  end

  # GET /orders/1/paid
  def paid
    order = Order.find(params[:id])
    order.status = "paid"
    order.save

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was updated status." }
    end
  end

  # GET /orders/1/completed
  def completed
    order = Order.find(params[:id])
    order.status = "completed"
    order.save

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was updated status." }
    end
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:address, :pay_type, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :pay_type %>

    <select name="order[pay_type]">
      <option value="CreditCard">Credit Card</option>
      <option value="Effective">Efective</option>
    </select>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Pay type</th>
      <th>Status</th>
      <th>Created date</th>
      <% if Current.user.is_admin %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.pay_type %></td>
        <td><%= order.status %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Show Order', order_path(order.id) %></td>
        <% if order.status == "ordered" %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <% end %>
        <% if order.status == "ordered" or order.status == "paid" %>
          <td><%= link_to 'Cancel', cancel_order_path(order) %></td>
        <% end %>
        <% if Current.user.is_admin %>
          <% if order.status == "ordered" %>
            <td><%= link_to 'Mark as paid', paid_order_path(order) %></td>
          <% end %>
          <% if order.status == "paid" %>
            <td><%= link_to 'Mark as completed', completed_order_path(order) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <aside id="notice"><%= notice %></aside>
  </div>
<% end %>

<h1>Order</h1>

<div>
  Address: <%= Current.order_selected.address %>
</div>


<table class="container">
  <thead>
  <tr>
    <th></th>
    <th>Description</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  </thead>

  <tbody>
  <% @line_items.each do |line_item| %>
    <tr style="border-bottom: 1px solid black;">
      <td><%= image_tag(line_item.food.photo, height:  '100', width: '100') %></td>
      <td><%= line_item.food.title %></td>
      <td><%= number_to_currency(line_item.price) %></td>

      <% if line_item.quantity != nil %>
      <td><%= line_item.quantity %></td>
        <% else %>
        <td>1</td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<div style="text-align: center;">
  Subtotal: <%= number_to_currency(Current.sub_total) %>
</div>
<br>

<div style="display: inline-block">
  <% if @line_items.length > 0 %>
    <%= link_to 'Regresar', orders_path, :class => 'btn btn-primary' %>
  <% end %>
</div>