config/routes.rb
Rails.application.routes.draw do
  #resources :orders
  #get 'orders/index'
  #get 'order/show'
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'

  root 'store#index', as: 'store_index'
  resources :line_items
  #resources :carts
  get 'cart', to: 'carts#index'
  post 'carts', to: 'carts#create', as: 'cart_checkout'

  get 'line_items/index'
  get 'line_items/show'
  get 'line_items/new'
  get 'line_items/create'
  post 'line_items/destroy', to: 'line_items#destroy', as: 'delete_line_item'
  get 'store/index', as: 'store_index_path'

  #resources :line_items, except: :edit
  #resources :line_items, only: :edit
  resources :users
  resources :foods
  resources :categories

  get '/login', to: 'sessions#login', as: 'login'
  post 'login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :orders, only: [:index, :show, :edit, :update] do
    member do
      get :cancel
      get :paid
      get :completed
    end
    collection do
      get :cancel_all
    end
  end
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  before_action :calculate_subtotal_cart

  # GET /carts or /carts.json
  def index
    if Current.cart
      @line_items = LineItem.where(cart_id: Current.cart.id)

      @pagy, @records = pagy(@line_items, items: 5)
      if @line_items.count == 0
        flash[:notice] = "Cart is empty!!"
      end
    end
  end

  # GET /carts/1 or /carts/1.json
  def show
    @line_items = LineItem.all
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    params.each do |param|
      if param[0].include? "line-item_"
        line_item = LineItem.find(param[0].split(/_/)[1])
        line_item.quantity = param[1]
        line_item.save
      end
    end
    @cart = Cart.find(params[:cart_id])

    respond_to do |format|
      if helpers.logged_id?
        line_items = LineItem.where(:cart_id => Current.cart.id)
        user = User.find_by_id(Current.user.id)
        order = Order.new(address: '', pay_type: '', user_id: user.id)
        order.status = "ordered"
        order.save
        line_items.each { |line_item|
          line_item.order_id = order.id
          line_item.save
        }
        @cart.pending = false
        @cart.save
        session.delete(:cart_id)
        session.delete(:count_food)

        format.html { redirect_to edit_order_path(order.id), notice: "Checkout cart successful. Your order is #{order.id}" }
      else
        format.html { redirect_to login_path, notice: "Logging is needed for checkout cart." }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to cart_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <aside id="notice"><%= notice %></aside>
  </div>
<% end %>

<h1>Cart</h1>

<% if @records %>
  <form action="/carts" method="post">
    <input type="hidden" name="cart_id" value="<%= @line_items.first().cart_id %>">
<table class="container">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @records.each do |line_item| %>
    <tr style="border-bottom: 1px solid black;">
      <td><%= image_tag(line_item.food.photo, height:  '100', width: '100') %></td>
      <td><%= line_item.food.title %></td>
      <td><%= number_to_currency(line_item.price) %></td>
      <td>
        <select name="line-item_<%= line_item.id %>">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
      </td>
      <td><%= line_item.quantity %></td>
      <td>
      <%= button_to 'Delete product', delete_line_item_path(line_item_id: line_item.id), :class => 'btn btn-primary' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div style="text-align: center;">
  Subtotal: <%= number_to_currency(Current.sub_total) %>
</div>
<%== pagy_bootstrap_nav(@pagy) %>
<br>

<div style="display: inline-block">
  <% if @line_items.length > 0 %>
    <button type="submit" class="btn btn-primary">Checkout</button>
  <% end %>
</div>

<div style="display: inline-block">
  <%= link_to 'Continue shopping', store_index_path, :class => 'btn btn-secondary' %>
</div>

  </form>
<% else %>
  Cart is empty!!
  </br>
  <div style="display: inline-block">
    <%= link_to 'Continue shopping', store_index_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
  <tr>
    <th>Food</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @line_items.each do |line_item| %>
    <tr>
      <td><%= line_item.food.title %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Checkout', new_cart_path(food_id: @line_items) %>
<%= link_to 'Checkout', cart_path(@line_items) %>