config/routes.rb
Rails.application.routes.draw do
  #resources :orders
  #get 'orders/index'
  #get 'order/show'
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'

  root 'store#index', as: 'store_index'
  resources :line_items
  #resources :carts
  get 'cart', to: 'carts#index'
  post 'carts', to: 'carts#create', as: 'cart_checkout'

  get 'line_items/index'
  get 'line_items/show'
  get 'line_items/new'
  get 'line_items/create'
  post 'line_items/destroy', to: 'line_items#destroy', as: 'delete_line_item'
  get 'store/index', as: 'store_index_path'

  #resources :line_items, except: :edit
  #resources :line_items, only: :edit
  resources :users
  resources :foods
  resources :categories

  get '/login', to: 'sessions#login', as: 'login'
  post 'login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :orders, only: [:index, :show, :edit, :update] do
    member do
      get :cancel
      get :paid
      get :completed
    end
    collection do
      get :cancel_all
    end
  end
  #get 'order/new'
  #get 'order/create'
  #get 'orders', to: 'order#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :food
  belongs_to :cart
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  #before_action :set_cart, only: [:create]
  before_action :set_line_item, only: %i[ show edit update ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    food = Food.find(params[:food_id])
    unless Current.cart
      cart = Cart.new(user_id: Current.user.id, pending: true)
      cart.save
      Current.cart = cart
    end
    cart = Cart.find(Current.cart.id)
    cart.pending = true
    cart.save
    @line_item = LineItem.new(cart_id: Current.cart.id, food_id: food.id, price: food.price, quantity: 1)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_path, notice: "Line item was successfully created." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:line_item_id])

    respond_to do |format|
      if @line_item.destroy
        format.html { redirect_to cart_path, notice: "Line item was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:food_id, :cart_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :food_id %>
    <%= form.text_field :food_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.food_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @line_item.food_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>